version: "3.8"

services:
  mysql:
    image: mysql:8.3
    container_name: mysql-familias-dev
    environment:
      MYSQL_DATABASE: cad_familias
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3307:3306"  # Porta diferente para não conflitar com a produção
    volumes:
      - mysql_data_dev:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uadmin -padmin123"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: cad-familias-dev
    ports:
      - "8081:8080" # Porta diferente para não conflitar com a produção
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_DATABASE: cad_familias
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      SPRING_PROFILES_ACTIVE: local
    volumes:
      - .:/app  # Para ter hot reload no desenvolvimento
    networks:
      - app-network

volumes:
  mysql_data_dev:

networks:
  app-network:
    driver: bridge
