spring.application.name=cad_familias_backend
spring.security.user.name=cad
spring.security.user.password=cad

cors.allowed-origins=http://localhost:4200
cors.allow-headers=authtoken, refreshtoken, Content-Type
cors.allow-methods=GET, POST, PUT, DELETE, OPTIONS
cookie.authtoken.maxAge=3600
cookie.refreshToken.maxAge=604800


jwt.secret=12345678